FEAT: 보험금 청구(1/5) 화면 구현
Kusitms-FITPET-DEV/FITPET_Android pull request #33
Opened 2024-09-02 06:51 UTC by emjayMJkim

## 이슈 번호
> 작업이 완료된 이슈의 번호를 기록해주세요.
- closed #28 

## 작업내용
> 작업한 내용을 설명해주세요. 왜 수정했는지? 무엇을 구현했는지? 등등
- 보험금 청구 원인 선택 로직 구현
- 캘린더 구현
- 캘린더 날짜 선택 구현
- 원인 및 날짜 모든 입력 완료 시 버튼 활성화 로직 구현
- 버튼 활성화 시 보험금 청구(2/5) 이동 

## 결과물
> 구현한 것 스크린샷 또는 영상 또는 gif 형태로 올려주세요.

https://github.com/user-attachments/assets/21e77268-5879-4c02-bb25-052ca7b21fff

## 리뷰어에게 추가로 요구하는 사항(선택)
> 이 부분을 자세히 봐야한다 또는 함수 로직에 확신이 없는데 더 좋은 방법이 있을까요? 등등

InsuranceTempAcrivity는 테스트용으로 생성해놓았습니다. 추후 홈 메인 기능을 MainActivity로 이전한 후 "보험생활" 화면에서 "보험금 청구" 화면 이동 연결하면 해당 파일은 삭제 예정입니다.

2024-09-02 07:40 UTC, Ssamssamukja commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/InsuranceChargeCauseFragment.kt
> +        Timber.d("[보험금 청구: 1/5] 캘린더 바텀시트")
오호 Timber라는 친구가 있군요! 잘 사용해보겠습니다!

2024-09-02 08:19 UTC, Ssamssamukja approved these changes
수고하셨습니당!! 👍

2024-09-02 14:51 UTC, dogmania requested changes
고생하셨습니다! 버그 우선적으로 수정해주세요

2024-09-02 14:51 UTC, dogmania commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/calendar/CalendarBottomSheet.kt
![image](https://github.com/user-attachments/assets/e206beaf-7330-4395-b09e-208328349bae)

오른쪽 화살표 버튼 색상이 다릅니다! 수정해주세요

2024-09-02 14:51 UTC, dogmania commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/InsuranceChargeCauseFragment.kt
> +                            getString(R.string.insurance_charge_cause_etc) -> tvInsuranceChargeCauseEtc.setTextAppearance(R.style.b4_S)
이렇게 구현하는 것도 좋지만 이렇게 하게 되면 UI와 로직이 결합되게 됩니다. 통원, 입원/수술, 기타 중 어떤 것을 선택했는지 알 수 있도록 상태 변수를 하나 만들고 상태 변수의 값에 따라 textAppearance를 수정하도록 data binding을 적용해주세요.

2024-09-02 14:51 UTC, dogmania commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/InsuranceChargeCausePageState.kt
> +    val selectedCause: StateFlow<String>,
여기에 상태 변수를 잘 선언해두었으니, 사용자가 이유를 선택할 때마다 xml에서 뷰모델 함수 호출해서 상태 업데이트 해주시고 업데이트된 상태와 삼항연산자를 결합하여 textAppearance를 변경해주세요

2024-09-02 14:51 UTC, dogmania commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/calendar/CalendarAdapter.kt
> +    var selectedPosition: Int = RecyclerView.NO_POSITION
position 같은 상태 변수들은 가급적이면 상태 변수로 선언해서 뷰모델에서 관리하는 게 좋아요!

2024-09-02 14:51 UTC, dogmania commented on app/src/main/res/layout/fragment_insurance_charge_document.xml
> +            android:text="서류 등록"
string.xml에 선언해서 사용해주세요

2024-09-02 18:18 UTC, emjayMJkim commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/calendar/CalendarBottomSheet.kt
이거 피그마에 좌우 화살표 색상 다르게 되어 있습니다!

2024-09-02 18:19 UTC, emjayMJkim commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/InsuranceChargeCauseFragment.kt
> +                            getString(R.string.insurance_charge_cause_etc) -> tvInsuranceChargeCauseEtc.setTextAppearance(R.style.b4_S)
style 리소스 옵션의 경우 XML 데이터바인딩에서 지원하고 있지 않기 때문에 삼항연산자로 사용이 불가능합니다! 따라서 BindingAdapter 만들어서 XML에서 사용하는 것으로 코드 수정했습니다

2024-09-02 18:20 UTC, emjayMJkim commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/InsuranceChargeCausePageState.kt
> +    val selectedCause: StateFlow<String>,
위 댓글에 설명 달았습니다!

2024-09-02 18:20 UTC, emjayMJkim commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/calendar/CalendarAdapter.kt
> +    var selectedPosition: Int = RecyclerView.NO_POSITION
넵 수정했습니다

2024-09-02 18:22 UTC, emjayMJkim commented on app/src/main/res/layout/fragment_insurance_charge_document.xml
> +            android:text="서류 등록"
앗 이 부분은 화면 전환 테스트용으로 만든 것이라 보험금 청구(2/5) 페이지 구현할 때 바로 삭제할 예정이라서 string 선언하지 않았습니다..!!

2024-09-03 00:05 UTC, dogmania commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/calendar/CalendarBottomSheet.kt
저 의도가 미래 날짜 선택하는 거 방지하기 위해 현재 날짜의 월과 동일하면 저렇게 처리하는 것으로 알고 있어요

2024-09-03 00:09 UTC, dogmania commented on app/src/main/java/com/example/fitpet/ui/insurance/charge/cause/InsuranceChargeCauseFragment.kt
> +                            getString(R.string.insurance_charge_cause_etc) -> tvInsuranceChargeCauseEtc.setTextAppearance(R.style.b4_S)
네 감사합니다!

2024-09-03 01:06 UTC, dogmania commented on app/src/main/res/layout/fragment_insurance_charge_document.xml
> +            android:text="서류 등록"
그런 거라면 tools:text를 사용해주세요! 의도를 알 수도 있고 테스트에 사용하기에 적합합니다

2024-09-03 11:28 UTC, dogmania approved these changes

2024-09-03 13:19 UTC, merged